config/routes.rb
DanAlexanderAudio::Application.routes.draw do
  resources :infos

  get "home/index"

  root :to => 'home#index'

end

app/models/info.rb
class Info < ActiveRecord::Base
  attr_accessible :title, :description, :date_uploaded, :infotype, :attachment

  validates :title, :presence => true,
                    :length => {:minimum => 5},
                    :uniqueness => true
  validates :description, :presence => true
  validates :date_uploaded, :presence => true
  validates :infotype, :presence => true

  has_attached_file :attachment, :styles => { :large => "500x500", :thumb => "100x100>" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/infos_controller.rb
class InfosController < ApplicationController
  # GET /infos
  # GET /infos.json
  def index
    @infos = Info.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @infos }
    end
  end

  # GET /infos/1
  # GET /infos/1.json
  def show
    @info = Info.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @info }
    end
  end

  # GET /infos/new
  # GET /infos/new.json
  def new
    @info = Info.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @info }
    end
  end

  # GET /infos/1/edit
  def edit
    @info = Info.find(params[:id])
  end

  # POST /infos
  # POST /infos.json
  def create
    @info = Info.new(params[:info])

    respond_to do |format|
      if @info.save
        format.html { redirect_to @info, notice: 'Info was successfully created.' }
        format.json { render json: @info, status: :created, location: @info }
      else
        format.html { render action: "new" }
        format.json { render json: @info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /infos/1
  # PUT /infos/1.json
  def update
    @info = Info.find(params[:id])

    respond_to do |format|
      if @info.update_attributes(params[:info])
        format.html { redirect_to @info, notice: 'Info was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /infos/1
  # DELETE /infos/1.json
  def destroy
    @info = Info.find(params[:id])
    @info.destroy

    respond_to do |format|
      format.html { redirect_to infos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/infos/_form.html.erb
<%= form_for(@info) do |f| %>
  <% if @info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@info.errors.count, "error") %> prohibited this info from being saved:</h2>

      <ul>
      <% @info.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :date_uploaded %><br />
    <%= f.date_select :date_uploaded %>
  </div>
  <div class="field">
    <%= f.label :infotype %><br />
    <%= f.select(:infotype, [['Publication', 1], ['Schematic', 2], ['Catalog', 3], ['Personal Showcase', 4]]) %>
  </div>
  <div class="field">
    <%= f.label :attachment %><br />
    <%= f.file_field :attachment %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/infos/edit.html.erb
<h1>Editing info</h1>

<%= render 'form' %>

<%= link_to 'Show', @info %> |
<%= link_to 'Back', infos_path %>

app/views/infos/index.html.erb
<h1>Listing infos</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Date uploaded</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @infos.each do |info| %>
  <tr>
    <td><%= info.title %></td>
    <td><%= info.description %></td>
    <td><%= info.date_uploaded %></td>
    <td><%= link_to 'Show', info %></td>
    <td><%= link_to 'Edit', edit_info_path(info) %></td>
    <td><%= link_to 'Destroy', info, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Info', new_info_path %>

app/views/infos/new.html.erb
<h1>New info</h1>

<%= render 'form' %>

<%= link_to 'Back', infos_path %>

app/views/infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @info.title %>
</p>

<p>
  <b>Description:</b>
  <%= @info.description %>
</p>

<p>
  <b>Date uploaded:</b>
  <%= @info.date_uploaded %>
</p>

<p>
  <b>Type:</b>
  <%= @info.infotype %>
</p>

<p>
  <b>File:</b>
  <%= image_tag @info.attachment.url(:large) %>
</p>


<%= link_to 'Edit', edit_info_path(@info) %> |
<%= link_to 'Back', infos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DanAlexanderAudio</title>
  <%= stylesheet_link_tag    "bootstrap", :media => "all" %>
  <%= javascript_include_tag "bootstrap" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="brand pull-left" href="<%= home_index_path %>">DanAlexanderAudio.com</a>
      <ul class="nav">
        <li class="divider-vertical"></li>
        <li><a href="<%= new_info_path %>">New Info</a></li>
        <li><a href="<%= infos_path %>">View Info</a></li>
      </ul>
    </div>
  </div>
</div>
<div class="container" style="padding-top:50px;">
<%= yield %>
</div>
</body>
</html>